CREATE TABLE OCNAS_SESSION (
  SESSION_ID CHAR(36),
  CREATION_TIME BIGINT NOT NULL,
  LAST_ACCESS_TIME BIGINT NOT NULL,
  MAX_INACTIVE_INTERVAL INT NOT NULL,
  PRINCIPAL_NAME VARCHAR(100),
  CONSTRAINT OCNAS_SESSION_PK PRIMARY KEY (SESSION_ID)
) 
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX OCNAS_SESSION_IX1 ON OCNAS_SESSION (LAST_ACCESS_TIME);

CREATE TABLE OCNAS_SESSION_ATTRIBUTES (
  SESSION_ID CHAR(36),
  ATTRIBUTE_NAME VARCHAR(200),
  ATTRIBUTE_BYTES BLOB,
  CONSTRAINT OCNAS_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_ID, ATTRIBUTE_NAME),
  CONSTRAINT OCNAS_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_ID) REFERENCES OCNAS_SESSION(SESSION_ID) ON DELETE CASCADE
) 
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX OCNAS_SESSION_ATTRIBUTES_IX1 ON OCNAS_SESSION_ATTRIBUTES (SESSION_ID);
